
<div class="pathway clearfix">
	<?php echo $this->action('youarehere','html',null,array('YouAreHere'=>$this->YouAreHere))?>
</div>
<!--[pathway]-->
<?php echo $this->partial('index/boxbanner2.phtml')?>
<?php echo $this->partial('index/boxtopcenter.phtml')?>
<div class="block">
	<div class="head clearfix">
		<h3 class="icon-customer"><?php echo $this->Khachhang->title ?></h3>
	</div>
	<!--//head-->

	<div class="content">

		<div class="introduction">
			<br>
                    	
                        	<?php echo $this->Khachhang->detail ?></div>
	</div>
</div>
<!--[block]-->
