<div class="pathway clearfix">
	<?php echo $this->action('youarehere','html',null,array('YouAreHere'=>$this->YouAreHere))?>
</div>
<!--[pathway]-->
<?php echo $this->partial('index/boxbanner2.phtml')?>
<?php echo $this->partial('index/boxtopcenter.phtml')?>
<div class="twocols clearfix">
	<div class="maincol">
		<div class="article">
			<h1><?php echo $this->NewsKienthuc->title; ?></h1>
			<i class="datepost">( <?php echo $this->NewsKienthuc->getDateAdd() ?> )</i><br>
			<div class="textintro">
                            	<?php echo $this->NewsKienthuc->description; ?>
                            </div>
			<div class="desccontainer">
                            	<?php echo $this->NewsKienthuc->detail; ?>
                            </div>
			<p align="right">
				<b><?php echo $this->NewsKienthuc->author ?></b>
			</p>
		</div>
		<!--[article]-->
		<div class="gotop">
			<a href="<?php echo $this->NewsKienthuc->getLinkKhuyenmai() ?>">Lên
				đầu trang</a>
		</div>
	</div>
	<!--e: div.mailcol-->
	<div class="rightcol">
		<div class="folder">
			<div class="head">
				<h3>Tin khác</h3>
			</div>
			<div class="content">
				<ul class="folder-list">
                            	<?php foreach ($this->NewsList as $NewsList){ ?>
                                	<li><div class="ui-inner">
							<div class="photo">
								<a href="<?php echo $NewsList->getLinkKhuyenmai() ?>"><img
									src=<?php echo $NewsList->getThumbImage() ?> height="26"
									width="36"></a>
							</div>
							<a href="<?php echo $NewsList->getLinkKhuyenmai() ?>"
								class="a-link"><?php echo $NewsList->title ?> </a><br> <i
								class="datepost">( <?php echo $NewsList->getDateAdd() ?> )</i>
						</div></li>
                                    <?php } ?>
                                </ul>
				<p class="more" align="right">
					<a href="<?php echo $this->url(array(),'news');?>">Xem thêm...</a>
				</p>
			</div>
		</div>
		<!--[folder]-->
		<div class="advright">
			<a href="#" style="display: block"><img src="images/img-04.jpg"
				height="261" width="211"></a>
		</div>
		<!--[advright]-->
	</div>
	<!--e: div.rightcol-->
</div>
<!--[twocols]-->

