<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(' - '.Zend_Registry::get ( 'Setting')->WEBSITE_NAME); ?>

<?php echo $this->headMeta(); ?>

<base href="<?php echo DOMAIN?>" />
<link type="text/css" rel="stylesheet" href="css/style.css" />
<script type="text/javascript">
var DOMAIN_NAME = 'http://<?php echo $_SERVER['HTTP_HOST'].$this->baseUrl()?>';
	
</script>

<!-- slide banner -->
	<link rel="stylesheet" href="css/slidebanner/bjqs.css">

    <!-- some pretty fonts for this demo page - not required for the slider -->
    <link href='http://fonts.googleapis.com/css?family=Source+Code+Pro|Open+Sans:300' rel='stylesheet' type='text/css'> 

    <!-- demo.css contains additional styles used to set up this demo page - not required for the slider --> 
    <link rel="stylesheet" href="css/slidebanner/demo.css">

    <!-- load jQuery and the plugin -->
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="js/slidebanner/bjqs-1.3.min.js"></script>	
<!-- end sliderbanner -->	
</head>

<body>
<div id="pagewidth" class="corner-all">
	<div id="header">
    	<div class="top clearfix">
    		<a class="FloatLeft" href="#"><img src="images/logo.png" /></a>
            <div class="search">
            	<form method="POST" action="tim-kiem.html">
            	<table cellpadding="0" cellspacing="0" border="0">
                	
                	<tr><td><input type="text" class="inputsearch" name="keyword"  
                	onblur="if (this.value=='') this.value='Gõ từ khóa tìm kiếm';" onfocus="if (this.value=='Gõ từ khóa tìm kiếm') this.value='';" value="Gõ từ khóa tìm kiếm">
                	</td>
                    	<td><input type="submit" class="imgeearch" value="Tìm kiếm" /></td>
                    </tr>
                    
                </table>
                </form>
            </div>
            <div class="support">
            	<img src="images/icon-phone.png" />
                <h2>Điện thoại hỗ trợ khách hàng</h2>
                <h1><?php $set= Settings::getAll() ;?>
                		<?php echo $set[2][value];?>
                </h1>
            </div>
            <div class="clearfix"></div>
        </div><!--@top-->
        <div class="navtop line">
        	<ul>
        		<li><a href="." class="cur">Trang chủ</a></li>
            	<li><a href="<?php echo $this->url(array(),'content') ?>">Giới thiệu</a></li>
                <li><a href="<?php echo $this->url(array(),'news') ?>">Tin tức</a></li>
                <li><a href="<?php echo $this->url(array(),'products') ?>">Tranh nghệ thuật</a></li>
                <li><a href="<?php echo $this->url(array(),'contact') ?>">Liên hệ</a></li>
            </ul>
        </div><!--@navtop-->
    </div><!--E: div#header-->
    <div id="bg">
        <div id="center"><div class="clearfix maincontent">
            <div class="banner"><?php echo $this->render('index/boxbanner2.phtml');?></div><!--end_banner-->
            <div class="you-are-here">
                <img src="images/icon/icon-02.gif" />
                <a href="#">Trang chủ</a>
            </div><!--end_you-are-here-->
            
            <div class="pathway clearfix">
            
				<?php echo $this->action('youarehere','html',null,array('YouAreHere'=>$this->YouAreHere))?>
			</div>
			
			
			
            <div class="leftcol">
            <div class="otherproduct">
                    <h3>Sản phẩm khác</h3>
                    
                    <ul>
                    <?php foreach ($this->ListPro as $List){ ?>
                    	<li>
                        	<p><a href="<?php echo $List->getLink() ?>"><img height="130" width="200" src="<?php echo $List->getThumbImage() ?>" /></a></p>
                            <p class="titlelink"><a href="<?php echo $List->getLink() ?>"><?php echo $List->title ?></a>Mã sản phẩm: <b><?php echo $List->origin;?></b></p>
                        </li>
                     <?php }?>   
                    </ul>
                   <div class="more-product"><a href="<?php echo $this->url(array(),'products') ?>">Xem thêm...</a></div> 
                    <div class="ClearBoth"></div>
                    
                </div><!--@otherproduct-->
                <?php $ad=Ads::getByLocation(2)?>
                
                <?php foreach($ad as $key){?>
                <?php if($key)?>
                <div class="ad1">
					<a href="<?php echo $key[link];?>">
					<img width="230" height="235" src="/uploads/<?php echo $key[file];?>"/>
					</a>
				</div>
				
				<?php }?>
            </div><!--e: div.leftcol-->
	            <div class="maincol">
	            	<?php echo $this->layout()->content;?>
	            </div><!--e: div.maincol-->
	            
          
            
        </div>
        
        </div><!--E: div#center-->
    </div><!--end_bg-->
  <div id="footer">
    	<div class="navbot">
        	<a href="index.html">Trang chủ</a> | <a href="introduction.html">Giới thiệu</a> | <a href="list.html">Tin tức</a> | <a href="product.html">Sản phẩm</a> | <a href="contact.html">Liên hệ</a>
        </div>
        <div class="copyright clearfix">
        	<span class="FloatLeft"><h2><?php echo $set[0][value]?></h2>
            	<?php echo $set[0][value]?><br />
                Điện thoại: <?php echo $set[2][value]?>   -  Website: <a href="#"><?php echo $set[4][value]?></a>
            </span>
            <span class="FloatRight"><a href="#"><img style="margin-top:10px" src="images/q.png" /></a></span>
        </div>
        
    </div><!--E: div#footer-->
</div>

</body>
</html>

