<?php
function ym($id) {
	$url = 'http://opi.yahoo.com/online?u=';
	$data = file_get_contents ( $url . $id );
	if (trim ( strtolower ( strip_tags ( $data ) ) ) != 'user not specified.') {
		return (strlen ( $data ) == 140) ? 'online' : 'offline';
	} else {
		return trim ( strip_tags ( $data ) );
	}
}
if (ym ( 'huonghoanglan_86' ) == 'online') {
	$img = 'images/yahoo.png';
} else {
	$img = 'images/yahoo_off.png';
}
function get_skype_status($username, $image = false, $icon = false) {
	// creating url
	// if you need small icon
	if ($image && $icon) {
		/**
		 * *************************************
		 * Possible types of images:
		 *
		 * balloon - Balloon style
		 * bigclassic - Big Classic Style
		 * smallclassic - Small Classic Style
		 * smallicon - Small Icon (transparent background)
		 * mediumicon - Medium Icon
		 * dropdown-white - Dropdown White Background
		 * dropdown-trans - Dropdown Transparent Background
		 * **************************************
		 */
		return "http://mystatus.skype.com/smallicon/" . $username;
	} 	// if you need image
	else if ($image) {
		return "http://mystatus.skype.com/" . $username;
	} 	// or just text
	else {
		/**
		 * *************************************
		 * Possible status values:
		 * NUM TEXT DESCRIPTION
		 * 0 UNKNOWN Not opted in or no data available.
		 * 1 OFFLINE The user is Offline
		 * 2 ONLINE The user is Online
		 * 3 AWAY The user is Away
		 * 4 NOT AVAILABLE The user is Not Available
		 * 5 DO NOT DISTURB The user is Do Not Disturb (DND)
		 * 6 INVISIBLE The user is Invisible or appears Offline
		 * 7 SKYPE ME The user is in Skype Me mode
		 * **************************************
		 */
		$url = "http://mystatus.skype.com/" . $username . ".xml";
		// getting contents
		$curl = curl_init ();
		curl_setopt ( $curl, CURLOPT_URL, $url );
		curl_setopt ( $curl, CURLOPT_RETURNTRANSFER, 1 );
		$data = curl_exec ( $curl );
		curl_close ( $curl );
		
		$pattern = '/xml:lang="en">(.*)</';
		preg_match ( $pattern, $data, $match );
		
		return $match [1];
	}
}
$skype = get_skype_status ( 'nhatduyen_art' );
if ($skype == 'Offline') {
	$imgskype = 'images/skype_off.png';
} elseif ($skype == 'Online') {
	$imgskype = 'images/skype.png';
}
?>

<div class="topcenter clearfix">
	<div class="support-online">
		<div class="sp-inner">
			<p>
				<a style="display: block" href="ymsgr:sendIM?huonghoanglan_86"> <img
					src='<?php echo $img ?>' />
				</a>
			</p>
			<p>
				<a style="display: block" href="skype:nhatduyen_art?chat"><img
					src="<?php echo $imgskype ?>"> </a>
			</p>
			<p>
				<img src="images/text.png">
			</p>
		</div>
	</div>
	<?php $Center= Ads::getWithOutPage(array('status=?'=>1,'location=?'=>1),1); ?>
	<?php $Right= Ads::getWithOutPage(array('status=?'=>1,'location=?'=>3),1); ?>
	<div class="advertising1">
		<a href="<?php echo $Center[0]->link ?>" target="_blank"
			style="display: block"><img
			src="uploads/<?php echo $Center[0]->file ?>" height="105" width="482">
		</a>
	</div>
	<div class="advertising2">
		<a href="<?php echo $Right[0]->link ?>" target="_blank"
			style="display: block"><img
			src="uploads/<?php echo $Right[0]->file ?>" height="105" width="248">
		</a>
	</div>
</div>
<!--[topcenter]-->
