<div class="hastable">
<div style="clear: both;">
<table cellspacing="0" cellpadding="0" width="100%">
	<thead>
		<tr>
			<th>Tiêu đề</th>
			<th>Tên khách hàng</th>
			<th>Email</th>
			<th>IP</th>			
			<th>Ngày tạo</th>
			<th>Xóa</th>
		</tr>
	</thead>
	<tbody>
				<?php $i=0; foreach($this->Contact as $Contact):?>
		<tr class="<?php ++$i; echo($i%2)?'first':'second'?>">
			<td><a href="<?php echo $this->url(array('controller'=>'contact','action'=>'view','id'=>$Contact->id))?>"><?php echo $Contact->id.' - '.$Contact->subject?></a></td>
			<td><?php echo $Contact->name?></td>
			<td><?php echo $Contact->email?></td>
			<td><?php echo $Contact->ip?></td>
			<td><?php echo $Contact->getCreatedDate()?></td>
			<td><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'contact','action'=>'delete','id'=>$Contact->id))?>"><span class="ui-icon ui-icon-circle-close"></span></a></td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>
<div class="paging"><?php echo $this->Pagination($this->Pager,'?page={%page}')?></div>
</div>
<div id="dialog-Review-view" title="Review detail">
<form>
<div id="dialog-Review-view_inner"></div>
</form>
</div>
</div>
<script type="text/javascript">
	(function() {
    initContentDialog();
	});
	$('#tim').val('<?php echo $this->filterType?>');

</script>