
	
		<table style="border-top:0">
			<tr>
				<td valign="top">
				<form action="" method="post" enctype="multipart/form-data">
				<div class="hastable">
				<table style="border-top:0">
						<tr>
							<td>Tiêu đề</td>
							<td colspan="3"><?php echo $this->formText('title',$this->Adv->title, array('style'=>'width:300px'))?></td>
						</tr>
						<tr>
							<td>Mô tả</td>
							<td colspan="3"><?php echo $this->formText('description',$this->Adv->description, array('style'=>'width:300px'))?></td>
						</tr>
						<tr>
							<!--td>Domain</td>
							<td><?php //echo $this->formSelect('domains_id',$this->Adv->domains_id,'',Domains::getOption(array('--Select--')))?>
							</td-->
							<td>Link chuyển đi</td>							
							<td colspan="3"><?php echo $this->formText('link',$this->Adv->link)?></td>
						</tr>
						<tr>
							<td>Width</td>							
							<td><?php echo $this->formText('width',$this->Adv->width)?></td>
							<td>height</td>							
							<td><?php echo $this->formText('height',$this->Adv->height)?></td>							
						</tr>
						<tr>
							<td>File</td>							
							<td><?php echo $this->formText('file',$this->Adv->file)?></td>
							<td>Trạng thái </td>
							<td><?php echo $this->formSelect('status',$this->Adv->status,'',array('Disable','Enable'))?></td>
						</tr>
						<tr>
							<td>Vị trí</td>
							<td colspan="3"><?php echo $this->formSelect('location',$this->Adv->location,'',Ads::$Location)?></td>
						</tr>
					</table>
					<?php echo $this->formSubmit('submit','Lưu lại')?><a href="javascript:history.back();"><input type="button" value="Quay lại"></input> </a>
					</div>	
					</form>
					</td>
					<td width="50%">
					<div class="hastable">
						<table style="border-top:0">
							<thead>
								<tr>
									<td>Danh sách thư viện</td>					
								</tr>
							</thead>
						<tbody style="overflow-y: auto; overflow-x: auto; height: 100%;">
						<?php foreach($this->Advs as $file):?>
							<tr>
								<td>
								<script>document.write(ParsedAdvHtml('/uploads/adv/<?php echo $file['name']?>','<?php echo $file['type']?>','','100%'));</script>
								Link: <?php echo $this->formText ( '','adv/'.$file['name'],array('size'=>'52'))?>
								</td>					
							</tr>
						<?php endforeach;?>
						</tbody>
						</table>
						</div>
					</td>
	
				</tr>			
			</table>

