<form method="get">
Thành viên: <?php echo $this->formSelect('id',$_REQUEST['id'],array(),Members::getOption(array(),array('--Select--')))?>
<?php echo $this->formSubmit('Xem','Xem nhật ký','page')?>
</form>
<div class="hastable">
<center><?php echo $this->error?></center>
<?php if($this->Log):?>
<table>
	<thead>
		<tr>
			<td>Thời điểm</td>
			<td>Phân mục</td>
			<td>Hành động</td>
			<td>IP</td>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->Log as $log):?>
		<tr>
			<td><?php echo $log['time']?></td>
			<td><?php echo $log['section']?></td>
			<td><?php echo $log['action']?></td>
			<td><?php echo $log['ip']?></td>
		</tr>
	<?php endforeach;?>
	</tbody>
</table>
<?php else:?>
Bạn hãy chọn thành viên muốn xem
<?php endif;?>
</div>
<div class="paging">
<?php for($i=1;$i<=$this->TotalPage;$i++):?>
  <a href="member/history?id=<?php echo $this->id?>&page=<?php echo $i?>"> <?php echo $i?></a>
<?php endfor;?>	</div>
