<?php

/**
 * Ads
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ads extends BaseAds {
	public static $Location = array (
			0 => 'Bander',
			'1' => 'Quảng cáo ở giữa',
			'2' => 'Quảng cáo bên trái',
			'3' => 'Quảng cáo bên phải',
			'4' => 'Bander2' ,
			'5'	=>'Trang chủ'
	);
	
	public function getLocation() {
		return self::$Location [$this->location];
	}
	
	public static function getAll($Condition = array(), $currentPage = 1, $recordPerPage, $order = 'status , id DESC') {
		
		$Adv = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( $order );
		foreach ( $Condition as $key => $item ) {
			$Adv->addWhere ( $key, $item );
		}
		$pager = new Doctrine_Pager ( $Adv, $currentPage, $recordPerPage );
		$Data = $pager->execute ();
		return array (
				$pager,
				$Data 
		);
	}
	
	public static function getWithOutPage($Condition = array(), $limit = 0) {
		$NewsCategories = Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'status=?', 1 )->orderBy ( 'id DESC' )->limit ( $limit );
		foreach ( $Condition as $key => $item ) {
			$NewsCategories->addWhere ( $key, $item );
		}
		return $NewsCategories->execute ();
	}
	
	public static function getById($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'id=?', $id )->execute ()->getFirst ();
	}
	
	public static function getByLocation($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'location=?', $id)->addWhere('status=?',1)->execute ();
	}
	
	public static function DeleteById($id = 0) {
		// echo Doctrine_Query::create ()->delete ( __CLASS__ )->where ( 'id=?',
		// $id )->getSqlQuery();
		Doctrine_Query::create ()->delete ( __CLASS__ )->where ( 'id=?', $id )->execute ();
	}
	
	public static function getAllByDomain($domain) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'status=1' )->addWhere ( 'domains_id=?', $domain )->execute ();
	}

}