<?php

/**
 * Contents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contents extends BaseContents {
	public static $Categories = array (
			'0' => 'Giới thiệu',
			'1' => 'Tin tức',
			'2' => 'Khuyến mãi',
			'3' => 'Khách hàng' 
	);
	public function getCategories() {
		return self::$Categories [$this->categories_id];
	}
	
	public static function getAll($Condition = array(), $currentPage = 1, $recordPerPage = 20, $orderBy = 'id DESC', $limit = 0) {
		
		$Hotel = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( $orderBy )->limit ( $limit );
		
		foreach ( $Condition as $key => $item ) {
			
			$Hotel->addWhere ( $key, $item );
		}
		
		$pager = new Doctrine_Pager ( $Hotel, $currentPage, $recordPerPage );
		$Data = $pager->execute ();
		
		return array (
				$pager,
				$Data 
		);
	}
	public static function getById($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'id=?', $id )->execute ()->getFirst ();
	}
	public static function getByNamePlain($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'title_plain=?', $id )->addWhere ( 'status=?', 1 )->execute ()->getFirst ();
	}
	public static function getByCategories($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'categories_id=?', $id )->execute ();
	}
	public function getCreatedDate() {
		return $this->created_date;
	}
	
	public function getLink() {
		return '/tin-tuc/' . $this->title_plain . '.html';
	}
	public function getLinkKhachhang() {
		return '/khach-hang/' . $this->title_plain . '.html';
	}
	public function getLinkKhuyenmai() {
		return '/khuyen-mai/' . $this->title_plain . '.html';
	}
	
	public function getNewsletter($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'id=?', $id )->execute ()->getFirst ();
	}
	public function getLocalizer() {
		return My_Plugin_Localizer::getLocalizer ( ContentLocalizer, $this );
	}
	
	public static function getWithOutPage($Condition = array(), $limit = 0) {
		$NewsCategories = Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'status=?', 1 )->orderBy ( 'id DESC' )->limit ( $limit );
		foreach ( $Condition as $key => $item ) {
			$NewsCategories->addWhere ( $key, $item );
		}
		return $NewsCategories->execute ();
	}
	public function getThumbImage() {
		return '/uploads/news/' . $this->id . '/thumb.jpg';
	}
	public function getDateAdd() {
		$time = date ( 'd-m-Y', strtotime ( $this->created_date ) );
		if ($time == '01-01-1970')
			return $this->created_date;
		else
			return date ( 'd/m/Y', strtotime ( $this->created_date ) );
	}

}