<?php

/**
 * Contact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contact extends BaseContact {
	public static function getAll($Condition = array(), $currentPage = 1, $recordPerPage = 20, $orderBy = 'id DESC') {
		$Hotel = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( $orderBy );
		foreach ( $Condition as $key => $item ) {
			$Hotel->addWhere ( $key, $item );
		}
		$pager = new Doctrine_Pager ( $Hotel, $currentPage, $recordPerPage );
		$Data = $pager->execute ();
		return array (
				$pager,
				$Data 
		);
	}
	public static function getById($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'id=?', $id )->execute ()->getFirst ();
	}
	public function getCreatedDate() {
		return date ( 'd/m/Y H:i:s', strtotime ( $this->created_date ) );
	}
	public function getLink() {
		return Zend_Registry::get ( 'Setting' )->DOMAIN . '/page/' . $this->id . '/' . $this->title_plain . Zend_Registry::get ( 'Setting' )->page_ext;
	}
	public static function checkLastActive() {
		if ($_SESSION ['Role'] ['contact'] ['index'] == '1') {
			$counter = Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'created_date>=?', $_SESSION ['Member']->last_login );
			if ($status != '')
				$counter->addWhere ( 'status=?', $status );
			$counter = $counter->count ();
			return ($counter) ? $counter : 0;
		}
	}
}