<?php

/**
 * Members
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Members extends BaseMembers {
	public static function setLogin($username = '000000', $pasword = '') {
		//print_r('dieee');die();
		$authAdapter = new Zend_Auth_Adapter_Doctrine_Table ( Doctrine::getConnectionByTableName ( 'Members' ) );
		//print_r('dafasd');die();
		$authAdapter->setTableName ( 'Members' )->setIdentityColumn ( 'username' )->setCredentialColumn ( 'password' )->setCredentialTreatment ( 'md5(?)' )->setIdentity ( $username )->setCredential ( $pasword );
		
		$auth = Zend_Auth::getInstance ();
		//print_r($authAdapter);die();
		$result =$auth->authenticate($authAdapter);
		//$result = $authAdapter->authenticate();
		if ($result->isValid ()) {
			$data = $authAdapter->getResultRowObject ( 'username', 'password' );
			$auth->getStorage ()->write ( $data );
			$Member = Members::getByUsername ( $auth->getIdentity ()->username );
			$Member->log ( 'Signed in', 'Members' );
			return $Member;
		} else {
			return false;
		}
	}
	
	public static function getAll($Condition = array(), $currentPage = 1, $recordPerPage = 10, $orderBy = 'id DESC') {
		$Customer = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( $orderBy );
		foreach ( $Condition as $key => $item ) {
			$Customer->addWhere ( $key, $item );
		}
		$pager = new Doctrine_Pager ( $Customer, $currentPage, $recordPerPage );
		$Data = $pager->execute ();
		return array (
				$pager,
				$Data 
		);
	}
	public static function getById($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'id=?', $id )->execute ()->getFirst ();
	}
	public static function getIdByUsername($username = '') {
		$User = Doctrine_Query::create ()->from ( __CLASS__ )->where ( "username=?", $username )->execute ()->getFirst ();
		return $User->id;
	}
	public static function getByUsername($username = '') {
		if ($username == '')
			return false;
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( "username='$username'" )->execute ()->getFirst ();
	}
	
	public static function getByEmail($username = '') {
		if ($username == '')
			return false;
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( "email='$username'" )->execute ()->getFirst ();
	}
	
	public static function toPassword($password = '') {
		return md5 ( $password );
	}
	public static function getOption($condition = array(), $data = array()) {
		$Countries = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( 'id' );
		foreach ( $condition as $key => $item ) {
			$Countries->addWhere ( $key, $item );
		}
		return self::toOptions ( $Countries->execute (), $data );
	
	}
	
	public function encodePassword() {
		$this->password = self::toPassword ( $this->password );
	}
	
	public static function toOptions($Members, $members) {
		foreach ( $Members as $User ) {
			$members [$User->id] = $User->username;
		}
		return $members;
	}
	
	public function getMemberType() {
		return Groups::getById ( $this->member_type )->name;
	}
	public function getCreatedDate() {
		return date ( 'd-m-Y H:i', strtotime ( $this->created_date ) );
	}
	public function getLastLogin() {
		return ($this->last_login) ? date ( 'd-m-Y H:i', strtotime ( $this->last_login ) ) : '-';
	}
	public function isSaler() {
		return ($this->member_type == 3) ? true : false;
	}
	public function log($message, $Controller) {
		return;
		$cvs_file = APPLICATION_PATH . 'data' . DIRECTORY_SEPARATOR . 'member_' . $this->id . '.log.csv';
		My_Plugin_Libs::appendCsv ( $cvs_file, array (
				date ( 'm-d-Y H:i:s', time () ),
				$_SERVER ['REMOTE_ADDR'],
				$Controller,
				$message 
		) );
	
	}
	public function setLastLogin() {
		$this->last_login = date ( 'Y-m-d H:i:s' );
		$this->save ();
	}
	public function getName() {
		return $this->name;
	}

}