<?php

/**
 * ProductType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class ProductType extends BaseProductType {
	
	public static function getAll($Condition = array(), $currentPage = 1, $recordPerPage = 10, $order = 'id DESC') {
		$Items = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( $order );
		if (count ( $Condition ))
			foreach ( $Condition as $key => $item ) {
				$Items->addWhere ( $key, $item );
			}
		$pager = new Doctrine_Pager ( $Items, $currentPage, $recordPerPage );
		$Data = $pager->execute ();
		return array (
				$pager,
				$Data 
		);
	}
	
	public static function getWithOutPage($Condition = array(), $limit = 0) {
		$Items = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( 'orders ASC' )->limit ( $limit );
		foreach ( $Condition as $key => $item ) {
			$Items->addWhere ( $key, $item );
		}
		return $Items->execute ();
	}
	
	public static function getById($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'id=?', $id )->execute ()->getFirst ();
	}
	
	public static function getByNamePlain($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'name_plain=?', $id )->execute ()->getFirst ();
	}
	public static function getOption($arr = array(), $condition = array()) {
		$Items = self::getWithOutPage ( $condition );
		foreach ( $Items as $Item ) {
			$arr [$Item->id] = $Item->name;
		}
		return $arr;
	}
}