<?php

/**
 * Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Users extends BaseUsers {
	
	public static function getAll($Condition = array(), $currentPage = 1, $recordPerPage = 20, $orderBy = 'id DESC') {
		$Users = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( $orderBy );
		foreach ( $Condition as $key => $item ) {
			$Users->addWhere ( $key, $item );
		}
		$pager = new Doctrine_Pager ( $Users, $currentPage, $recordPerPage );
		$Data = $pager->execute ();
		return array (
				$pager,
				$Data 
		);
	}
	
	public static function getById($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'id=?', $id )->execute ()->getFirst ();
	}
	
	public static function getByUsername($username = '') {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'username=?', $id )->addWhere ( 'status=?', 1 )->execute ()->getFirst ();
	}
	
	public static function getWithOutPage($Condition = array(), $limit = 0) {
		$Users = Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'status=?', 1 )->orderBy ( 'id DESC' )->limit ( $limit );
		foreach ( $Condition as $key => $item ) {
			$Users->addWhere ( $key, $item );
		}
		return $Users->execute ();
	}
	
	public function getThumbImage() {
		return '/uploads/users/' . $this->id . '/thumb.jpg';
	}
}