

<div class="block">
	<div class="head clearfix">
		<h3 class="icon-introduction">Giới thiệu</h3>
	</div>
	<!--//head-->
                    <?php //$Content= Contents::getWithOutPage(array('categories_id=?'=>0,'status=?'=>1),1)?>
                    <div class="content">

		<div class="introduction">
			<br>
                    	
                        	<?php echo $this->Content['detail']; ?></div>
	</div>
</div>
<!--[block]-->
